### ISSUE TITLE
Case: Login with discord failed if mobile number is used

### ISSUE THREAD

**Issue by ravisoni6262** [expresstechsoftware/pmpro-discord-add-on#10]
- If email is not found we will use the phone number.
- Also, it will generate a random email ID for the account. 
- Instead of email details we will display them after the login page/checkout.

**Comment by younes-dro** [comment]
@ravisoni6262 Could you please explain this further:
Instead of emailing details, we will display them after the login page/checkout.

**Comment by ravisoni6262** [comment]
@younes-dro In case email is not present in discord account details, `phone number is used` then we should 

1. Create a fake email with a random username `ancdedxyz@fakemail.com`

I belive it is sufficient to allow members to have accounts, rest it is okay to leave it to website admin, no need to display any information
