### ISSUE TITLE
CSS being added that is hiding payment fields and submit buttons.

### ISSUE THREAD

**Issue by kimwhite** [expresstechsoftware/pmpro-discord-add-on#298]
When the plugin is installed and activated, with no configuration, the checkout page payment fields and submit button is hidden.
It appears this .CSS is being inserted. 

`body.pmpro-checkout div#pmpro_user_fields, body.pmpro-checkout div#pmpro_billing_address_fields, body.pmpro-checkout div#pmpro_payment_information_fields, body.pmpro-checkout div.pmpro_submit {
    display: none!important;
}`

It appears to be coming from here:
https://github.com/expresstechsoftware/pmpro-discord-add-on/blob/59f6eb8574e3e484b0be0695fa22da1bfb94be23/includes/classes/class-pmpro-discord-admin-setting.php#L891

I have tested this with WordPress 6.0, TwentyTwenty theme, and only PMPro and Discord Add On are active.
<img width="1180" alt="Screen Shot 2022-06-08 at 12 51 37 PM" src="https://user-images.githubusercontent.com/8083630/172673082-c42579eb-af89-4e34-8a7d-d8396fe44458.png">

**Comment by ravisoni6262** [comment]
Hey @kimwhite 
We release a new version with a fix.
https://wordpress.org/plugins/pmpro-discord-add-on/
Thanks for catching this error.
